version: '3.7'

services:
  backend:
    build: ./be
    container_name: backend
    ports:
      - "9090:9090"
    environment:
      FLASK_ENV: development
      MONGO_URI: mongodb://mongo:27017/devops
    depends_on:
      - mongo

  frontend:
    build: ./fe
    container_name: frontend
    ports:
      - "7070:7070"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: devops
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
