apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 9090
          env:
            - name: FLASK_ENV
              value: "development"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/devops"
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 9090
  selector:
    app: backend
