apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          ports:
            - containerPort: 7070
          env:
            - name: NODE_ENV
              value: "development"
              # value: "production"
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 7070
  selector:
    app: frontend
