apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_DATABASE
              value: "devops"
          volumeMounts:
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-init
          configMap:
            name: mongo-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
  selector:
    app: mongo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-mongo.js: |
    db = connect("mongodb://localhost:27017/devops");

    var initialData = [
        {
            link: "http://example.com",
            name: "Tom",
            username: "No. 189, Grove St, Los Angeles",
            password: "aaaaaaaaaaa",
        },
        {
            link: "http://example.com",
            name: "Jerry",
            username: "No. 123, Elm St, New York",
            password: "123456",
        }
    ];

    var initialEvent = [
        {
            date: "2024-01-01",
            title: "Test",
            question: "Test",
            description: "Test",
            answer: "Test"
        },
        {
            date: "2024-01-01",
            title: "Test",
            question: "Test",
            description: "Test",
            answer: "Test"
        }
    ]

    db.link_list.insertMany(initialData);
    db.event.insertMany(initialEvent);

    print("Initial data inserted successfully");
